// Admin login
export const ADMIN_LOGIN_REQUEST = 'ADMIN_LOGIN_REQUEST'
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS'
export const ADMIN_LOGIN_FAIL = 'ADMIN_LOGIN_FAIL'
export const ADMIN_LOGOUT = 'ADMIN_LOGOUT'

// Admin Registration
export const ADMIN_REGISTER_REQUEST = 'ADMIN_REGISTER_REQUEST'
export const ADMIN_REGISTER_SUCCESS = 'ADMIN_REGISTER_SUCCESS'
export const ADMIN_REGISTER_FAIL = 'ADMIN_REGISTER_FAIL'

// Single Admin Details
export const ADMIN_DETAILS_REQUEST = 'ADMIN_DETAILS_REQUEST'
export const ADMIN_DETAILS_SUCCESS = 'ADMIN_DETAILS_SUCCESS'
export const ADMIN_DETAILS_FAIL = 'ADMIN_DETAILS_FAIL'
export const ADMIN_DETAILS_RESET = 'ADMIN_DETAILS_RESET'

// single Admin profile update
export const ADMIN_UPDATE_PROFILE_REQUEST = 'ADMIN_UPDATE_PROFILE_REQUEST'
export const ADMIN_UPDATE_PROFILE_SUCCESS = 'ADMIN_UPDATE_PROFILE_SUCCESS'
export const ADMIN_UPDATE_PROFILE_FAIL = 'ADMIN_UPDATE_PROFILE_FAIL'
export const ADMIN_UPDATE_PROFILE_RESET = 'ADMIN_UPDATE_PROFILE_RESET'

// All Admins
export const ADMIN_LIST_REQUEST = 'ADMIN_LIST_REQUEST'
export const ADMIN_LIST_SUCCESS = 'ADMIN_LIST_SUCCESS'
export const ADMIN_LIST_FAIL = 'ADMIN_LIST_FAIL'
export const ADMIN_LIST_RESET = 'ADMIN_LIST_RESET'

// single Admin Delete
export const ADMIN_DELETE_REQUEST = 'ADMIN_DELETE_REQUEST'
export const ADMIN_DELETE_SUCCESS = 'ADMIN_DELETE_SUCCESS'
export const ADMIN_DELETE_FAIL = 'ADMIN_DELETE_FAIL'

// Admin create instructor
export const ADMIN_CREATE_INSTRUCTOR_REQUEST = 'ADMIN_CREATE_INSTRUCTOR_REQUEST'
export const ADMIN_CREATE_INSTRUCTOR_SUCCESS = 'ADMIN_CREATE_INSTRUCTOR_SUCCESS'
export const ADMIN_CREATE_INSTRUCTOR_FAIL = 'ADMIN_CREATE_INSTRUCTOR_FAIL'

// Admin GET instructors
export const ADMIN_GET_INSTRUCTORS_REQUEST = 'ADMIN_GET_INSTRUCTORS_REQUEST'
export const ADMIN_GET_INSTRUCTORS_SUCCESS = 'ADMIN_GET_INSTRUCTORS_SUCCESS'
export const ADMIN_GET_INSTRUCTORS_FAIL = 'ADMIN_GET_INSTRUCTORS_FAIL'

// Admin GET SINGLE instructor
export const ADMIN_GET_INSTRUCTOR_REQUEST = 'ADMIN_GET_INSTRUCTOR_REQUEST'
export const ADMIN_GET_INSTRUCTOR_SUCCESS = 'ADMIN_GET_INSTRUCTOR_SUCCESS'
export const ADMIN_GET_INSTRUCTOR_FAIL = 'ADMIN_GET_INSTRUCTOR_FAIL'

// Admin UPDATE SINGLE instructor
export const ADMIN_UPDATE_INSTRUCTOR_REQUEST = 'ADMIN_UPDATE_INSTRUCTOR_REQUEST'
export const ADMIN_UPDATE_INSTRUCTOR_SUCCESS = 'ADMIN_UPDATE_INSTRUCTOR_SUCCESS'
export const ADMIN_UPDATE_INSTRUCTOR_FAIL = 'ADMIN_UPDATE_INSTRUCTOR_FAIL'

// Admin DELETE SINGLE instructor
export const ADMIN_DELETE_INSTRUCTOR_REQUEST = 'ADMIN_DELETE_INSTRUCTOR_REQUEST'
export const ADMIN_DELETE_INSTRUCTOR_SUCCESS = 'ADMIN_DELETE_INSTRUCTOR_SUCCESS'
export const ADMIN_DELETE_INSTRUCTOR_FAIL = 'ADMIN_DELETE_INSTRUCTOR_FAIL'

// Admin create SESSION
export const ADMIN_CREATE_SESSION_REQUEST = 'ADMIN_CREATE_SESSION_REQUEST'
export const ADMIN_CREATE_SESSION_SUCCESS = 'ADMIN_CREATE_SESSION_SUCCESS'
export const ADMIN_CREATE_SESSION_FAIL = 'ADMIN_CREATE_SESSION_FAIL'

// Admin GET SESSIONs
export const ADMIN_GET_SESSIONS_REQUEST = 'ADMIN_GET_SESSIONS_REQUEST'
export const ADMIN_GET_SESSIONS_SUCCESS = 'ADMIN_GET_SESSIONS_SUCCESS'
export const ADMIN_GET_SESSIONS_FAIL = 'ADMIN_GET_SESSIONS_FAIL'

// Admin GET SINGLE SESSION
export const ADMIN_GET_SESSION_REQUEST = 'ADMIN_GET_SESSION_REQUEST'
export const ADMIN_GET_SESSION_SUCCESS = 'ADMIN_GET_SESSION_SUCCESS'
export const ADMIN_GET_SESSION_FAIL = 'ADMIN_GET_SESSION_FAIL'

// Admin UPDATE SINGLE SESSION
export const ADMIN_UPDATE_SESSION_REQUEST = 'ADMIN_UPDATE_SESSION_REQUEST'
export const ADMIN_UPDATE_SESSION_SUCCESS = 'ADMIN_UPDATE_SESSION_SUCCESS'
export const ADMIN_UPDATE_SESSION_FAIL = 'ADMIN_UPDATE_SESSION_FAIL'

// Admin DELETE SINGLE SESSION
export const ADMIN_DELETE_SESSION_REQUEST = 'ADMIN_DELETE_SESSION_REQUEST'
export const ADMIN_DELETE_SESSION_SUCCESS = 'ADMIN_DELETE_SESSION_SUCCESS'
export const ADMIN_DELETE_SESSION_FAIL = 'ADMIN_DELETE_SESSION_FAIL'

// Admin create WORKOUT
export const ADMIN_CREATE_WORKOUT_REQUEST = 'ADMIN_CREATE_WORKOUT_REQUEST'
export const ADMIN_CREATE_WORKOUT_SUCCESS = 'ADMIN_CREATE_WORKOUT_SUCCESS'
export const ADMIN_CREATE_WORKOUT_FAIL = 'ADMIN_CREATE_WORKOUT_FAIL'

// Admin GET WORKOUTs
export const ADMIN_GET_WORKOUTS_REQUEST = 'ADMIN_GET_WORKOUTS_REQUEST'
export const ADMIN_GET_WORKOUTS_SUCCESS = 'ADMIN_GET_WORKOUTS_SUCCESS'
export const ADMIN_GET_WORKOUTS_FAIL = 'ADMIN_GET_WORKOUTS_FAIL'

// Admin GET SINGLE WORKOUT
export const ADMIN_GET_WORKOUT_REQUEST = 'ADMIN_GET_WORKOUT_REQUEST'
export const ADMIN_GET_WORKOUT_SUCCESS = 'ADMIN_GET_WORKOUT_SUCCESS'
export const ADMIN_GET_WORKOUT_FAIL = 'ADMIN_GET_WORKOUT_FAIL'

// Admin UPDATE SINGLE WORKOUT
export const ADMIN_UPDATE_WORKOUT_REQUEST = 'ADMIN_UPDATE_WORKOUT_REQUEST'
export const ADMIN_UPDATE_WORKOUT_SUCCESS = 'ADMIN_UPDATE_WORKOUT_SUCCESS'
export const ADMIN_UPDATE_WORKOUT_FAIL = 'ADMIN_UPDATE_WORKOUT_FAIL'

// Admin DELETE SINGLE WORKOUT
export const ADMIN_DELETE_WORKOUT_REQUEST = 'ADMIN_DELETE_WORKOUT_REQUEST'
export const ADMIN_DELETE_WORKOUT_SUCCESS = 'ADMIN_DELETE_WORKOUT_SUCCESS'
export const ADMIN_DELETE_WORKOUT_FAIL = 'ADMIN_DELETE_WORKOUT_FAIL'
